site_name: Graph4SupplyChain
site_description: A comprehensive supply chain analytics platform with graph neural networks and time series forecasting
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - footnotes

nav:
  - Home: index.md
  - Parser: Parser.md
  - GNN Based Forecasting: SingleStepGNN.md
  - Timeseries Forecasting: Timeseries.md
  - Bottleneck: Bottleneck.md
  - Sparsity: Sparsity.md
  - HybridData: HybridModel.md
  - TestPage: TestPage.md

extra:
  social:
    - type: github
      icon: fontawesome/brands/github-alt
      link: https://www.github.com/SANTHOSH-SACHIN/graph4supplychain